### ISSUE TITLE
Node.js 4.0.0 issue

### ISSUE THREAD

**Issue by youmustfight** [chootka/subnodes#10]
Bit of a newbie here, but it seems that packages in the January version of Raspbian are having issues with the latest deployment of Node(4.0.0). In **install.sh**, you have on lines 76: 
```
echo "Installing Node.js..."
wget http://node-arm.herokuapp.com/node_latest_armhf.deb
sudo dpkg -i node_latest_armhf.deb
```
Might be worth just switching *latest* to *archive*:
```
echo "Installing Node.js..."
wget http://node-arm.herokuapp.com/node_archive_armhf.deb
sudo dpkg -i node_archive_armhf.deb
```
for the 0.12.6 version.

Not sure how to approach this problem from the package end.

**Comment by chootka** [comment]
Hello,

Thanks for the heads up. I had a similar report from someone else. We are going to look at it sometime today, actually.
