### ISSUE TITLE
Mesh Network and AP from the single built-in wifi (RaspberryPi 3) (?)

### ISSUE THREAD

**Issue by suiluj** [chootka/subnodes#20]
I was able to run the Raspberry Pi 3 as a Wifi client (station) and access point (ap) from the single built-in wifi. See this instruction: https://github.com/peebles/rpi3-wifi-station-ap-stretch

Do you think it is possible to use the single built in wifi for the ap and b.a.t.m.a.n. mesh network?
So the wlan0 would change from client network to the b.a.t.m.a.n. mesh network.

Perhaps it is possible to use the additional uap0 interface (which uses the same internal wifi):

`/etc/udev/rules.d/90-wireless.rules`
```
ACTION=="add", SUBSYSTEM=="ieee80211", KERNEL=="phy0", \
    RUN+="/sbin/iw phy %k interface add uap0 type __ap"
```

**Comment by chootka** [comment]
Unfortunately it's not possible. The on-board radio is not capable of going into mesh or ad hoc mode. I always use a second USB wifi radio plugged into the RPi, which is capable of supporting mesh.

**Comment by samuk** [comment]
This list helped me find Mesh compatible USB's https://github.com/phillymesh/802.11s-adapters/blob/master/README.md

Would it be worth linking to it from the Submesh readme where you say "running the nl80211 driver"

**Comment by chootka** [comment]
Hi @samuk 

Sure, that's a good suggestion. I'll add it in.

Thanks!
