### ISSUE TITLE
npm problems

### ISSUE THREAD

**Issue by impshum** [chootka/subnodes#8]
Having little knowledge of npm... 
This happens when I run the install script, and following your tutorial.

sudo npm install
npm http GET https://registry.npmjs.org/jade
npm http 200 https://registry.npmjs.org/jade
npm http GET https://registry.npmjs.org/jade/-/jade-1.9.2.tgz
npm http 200 https://registry.npmjs.org/jade/-/jade-1.9.2.tgz
npm http GET https://registry.npmjs.org/void-elements
npm http GET https://registry.npmjs.org/with
npm http GET https://registry.npmjs.org/character-parser/1.2.1
npm http GET https://registry.npmjs.org/commander
npm http GET https://registry.npmjs.org/constantinople
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/transformers/2.1.0
npm http 200 https://registry.npmjs.org/void-elements
npm http 200 https://registry.npmjs.org/mkdirp
npm http 200 https://registry.npmjs.org/with
npm http 200 https://registry.npmjs.org/commander
npm http 200 https://registry.npmjs.org/character-parser/1.2.1
npm http 200 https://registry.npmjs.org/transformers/2.1.0
npm http GET https://registry.npmjs.org/void-elements/-/void-elements-2.0.1.tgz
npm http GET https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.0.tgz
npm http GET https://registry.npmjs.org/with/-/with-4.0.3.tgz
npm http GET https://registry.npmjs.org/commander/-/commander-2.6.0.tgz
npm http 200 https://registry.npmjs.org/constantinople
npm http GET https://registry.npmjs.org/character-parser/-/character-parser-1.2.1.tgz
npm http GET https://registry.npmjs.org/transformers/-/transformers-2.1.0.tgz
npm http 200 https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.0.tgz
npm http 200 https://registry.npmjs.org/void-elements/-/void-elements-2.0.1.tgz
npm http 200 https://registry.npmjs.org/transformers/-/transformers-2.1.0.tgz
npm http 200 https://registry.npmjs.org/commander/-/commander-2.6.0.tgz
npm http 200 https://registry.npmjs.org/with/-/with-4.0.3.tgz
npm http 200 https://registry.npmjs.org/character-parser/-/character-parser-1.2.1.tgz
npm http GET https://registry.npmjs.org/constantinople/-/constantinople-3.0.1.tgz
npm http 200 https://registry.npmjs.org/constantinople/-/constantinople-3.0.1.tgz
npm WARN engine void-elements@2.0.1: wanted: {"node":">=0.10.0"} (current: {"node":"v0.9.9","npm":"1.2.10"})
npm http GET https://registry.npmjs.org/acorn
npm http GET https://registry.npmjs.org/acorn-globals
npm http GET https://registry.npmjs.org/acorn-globals
npm http 200 https://registry.npmjs.org/acorn-globals
npm http 200 https://registry.npmjs.org/acorn
npm http 200 https://registry.npmjs.org/acorn-globals
npm http GET https://registry.npmjs.org/promise
npm http GET https://registry.npmjs.org/css
npm http GET https://registry.npmjs.org/uglify-js
npm ERR! Error: ENOENT, open '/home/pi/www/subnodes/node_modules/jade/node_modules/mkdirp/test/return_sync.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.18.7+
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /home/pi/www/subnodes
npm ERR! node -v v0.9.9
npm ERR! npm -v 1.2.10
npm ERR! path /home/pi/www/subnodes/node_modules/jade/node_modules/mkdirp/test/return_sync.js
npm ERR! code ENOENT
npm ERR! errno 34
npm http 200 https://registry.npmjs.org/promise
npm http 200 https://registry.npmjs.org/uglify-js
npm http 200 https://registry.npmjs.org/css
npm ERR! Error: No compatible version found: acorn-globals@'^1.0.3'
npm ERR! Valid install targets:
npm ERR! ["1.0.0","1.0.1","1.0.2","1.0.3","1.0.4"]
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:676:10)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:591:10
npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:93:15)
npm ERR!     at process._makeCallback (node.js:318:24)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.18.7+
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /home/pi/www/subnodes
npm ERR! node -v v0.9.9
npm ERR! npm -v 1.2.10
npm http GET https://registry.npmjs.org/promise/-/promise-2.0.0.tgz
npm http GET https://registry.npmjs.org/uglify-js/-/uglify-js-2.2.5.tgz
npm http GET https://registry.npmjs.org/css/-/css-1.0.8.tgz
npm http 200 https://registry.npmjs.org/promise/-/promise-2.0.0.tgz
npm http 200 https://registry.npmjs.org/css/-/css-1.0.8.tgz
npm http 200 https://registry.npmjs.org/uglify-js/-/uglify-js-2.2.5.tgz
npm http GET https://registry.npmjs.org/is-promise
npm http GET https://registry.npmjs.org/css-parse/1.0.4
npm http GET https://registry.npmjs.org/css-stringify/1.0.5
npm http 200 https://registry.npmjs.org/is-promise
npm http 200 https://registry.npmjs.org/css-parse/1.0.4
npm http 200 https://registry.npmjs.org/css-stringify/1.0.5
npm http GET https://registry.npmjs.org/is-promise/-/is-promise-1.0.1.tgz
npm http GET https://registry.npmjs.org/css-parse/-/css-parse-1.0.4.tgz
npm http GET https://registry.npmjs.org/css-stringify/-/css-stringify-1.0.5.tgz
npm http 200 https://registry.npmjs.org/is-promise/-/is-promise-1.0.1.tgz
npm http 200 https://registry.npmjs.org/css-stringify/-/css-stringify-1.0.5.tgz
npm http 200 https://registry.npmjs.org/css-parse/-/css-parse-1.0.4.tgz
npm http GET https://registry.npmjs.org/source-map
npm http GET https://registry.npmjs.org/optimist
npm http 200 https://registry.npmjs.org/optimist
npm http 200 https://registry.npmjs.org/source-map
npm http GET https://registry.npmjs.org/optimist/-/optimist-0.3.7.tgz
npm http GET https://registry.npmjs.org/source-map/-/source-map-0.1.43.tgz
npm http 200 https://registry.npmjs.org/optimist/-/optimist-0.3.7.tgz
npm http 200 https://registry.npmjs.org/source-map/-/source-map-0.1.43.tgz
npm http GET https://registry.npmjs.org/wordwrap
npm http 200 https://registry.npmjs.org/wordwrap
npm http GET https://registry.npmjs.org/wordwrap/-/wordwrap-0.0.2.tgz
npm http 200 https://registry.npmjs.org/wordwrap/-/wordwrap-0.0.2.tgz
npm http GET https://registry.npmjs.org/amdefine
npm http 200 https://registry.npmjs.org/amdefine
npm http GET https://registry.npmjs.org/amdefine/-/amdefine-0.1.0.tgz
npm http 200 https://registry.npmjs.org/amdefine/-/amdefine-0.1.0.tgz
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/www/subnodes/npm-debug.log
npm ERR! not ok code 0

------------------------------------------------------------------------

sudo npm install -g nodemon
npm http GET https://registry.npmjs.org/nodemon
npm http 304 https://registry.npmjs.org/nodemon
npm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/ps-tree
npm http GET https://registry.npmjs.org/touch
npm http GET https://registry.npmjs.org/update-notifier
npm http 304 https://registry.npmjs.org/minimatch
npm http 304 https://registry.npmjs.org/ps-tree
npm http 304 https://registry.npmjs.org/touch
npm http 304 https://registry.npmjs.org/update-notifier
npm ERR! Error: No compatible version found: update-notifier@'^0.3.0'
npm ERR! Valid install targets:
npm ERR! ["0.1.0","0.1.1","0.1.2","0.1.3","0.1.4","0.1.5","0.1.6","0.1.7","0.1.8","0.1.9","0.1.10","0.2.0","0.2.1","0.2.2","0.3.0","0.3.1","0.3.2"]
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:676:10)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:591:10
npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:93:15)
npm ERR!     at process._makeCallback (node.js:318:24)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.18.7+
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "nodemon"
npm ERR! cwd /home/pi/www/subnodes
npm ERR! node -v v0.9.9
npm ERR! npm -v 1.2.10
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/www/subnodes/npm-debug.log
npm ERR! not ok code 0

Many thanks in advance.

**Comment by chootka** [comment]
Hello, thanks for logging the issue. I will take a look at it.

**Comment by impshum** [comment]
Cool.

**Comment by Nodeswitch** [comment]
I had a similar issue. Seems to be related to having version 0.0.9 installed. If you use [0.11.12](http://nodejs.org/dist/v0.11.12/) instead, which is the last ARM version I can find on nodejs.org, the install works fine.

**Comment by chootka** [comment]
fixed with commit https://github.com/chootka/subnodes/commit/dfad6430c40edbebd4624d759e90b3e386de09b5
